<?php

namespace Blogger\BlogBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    public function getCommentsForBlog($blogId, $approved = true)
    {
        $qb = $this->createQueryBuilder('comment')
            ->select('comment')
            ->where('comment.blog = :blog_id')
            ->addOrderBy('comment.created')
            ->setParameter('blog_id', $blogId);

        if (false === is_null($approved))
            $qb->andWhere('comment.approved = :approved')
               ->setParameter('approved', $approved);

        return $qb->getQuery()->getResult();
    }
}